### ISSUE TITLE
Manual Passed/Failed in Quiz Mode

### ISSUE THREAD

**Issue by victor0d** [azizkayumov/Flashcard-Maker-Android#35]
First of all, thanks for bringing the app back alive and rewrite it in Kotlin.

I would suggest to have a manual way to set the card to pass or fail in quiz mode.

There are many cases where the user needs to double check the answer to self confirm he/she knows it. As it stands today, once you flip the card, it is automatically registered as wrong.

Thanks for your consideration

**Comment by azizkayumov** [comment]
Fixed in #37. Please update your app from Google Play
