### ISSUE TITLE
Annoying text editing function

### ISSUE THREAD

**Issue by greyboxgt** [azizkayumov/Flashcard-Maker-Android#36]
There are four icons in the corners of the editing module (edit, archive, check and rotation icons). I use these icons a lot, and I often miss a little bit and initiate the unwanted text editing procedure. Could you please disable the call for text editing after clicking on the screen? We still should be able to click on the edit icon (pencil) and select "Edit text" to do the same thing. I know this might look like a minor thing, but to me it would be a big deal.

Thank you!!

**Comment by azizkayumov** [comment]
Thank you for your feedback. 
Yeah, this should be the right behavior. I am just getting back to where the app used to be, I will fix it in the next commit.
