### ISSUE TITLE
Archive issue

### ISSUE THREAD

**Issue by greyboxgt** [azizkayumov/Flashcard-Maker-Android#40]
After the latest updates, the Archive function no longer works properly for me. When I click on the "archive" icon (the right top icon) in the Editing module, the new set with the same name in the "All sets" area is created instead of in the "Archive" area.

**Comment by azizkayumov** [comment]
Thank you for your feedback. I tried the archive function, but it seems to work in my case. Can you please comment the steps to reproduce this bug in more details?

**Comment by azizkayumov** [comment]
If you click the "archive" icon in an "archived" set editor, it will create the "original" set in "All sets" area. The opposite happens if you click the "archive" icon in the "original" set.  I guess the former is your case, let me know if this helps.

**Comment by greyboxgt** [comment]
It used to work as you described, but now the archive sets with exactly same name is created in the "All sets" area, the "Archive" area is ignored. Nothing is created or updated in the "Archive" area after clicking the "archive" icon. Looks like a bug to me. My version is 0.3.6.

**Comment by Engineerator** [comment]
The Archive function is not working for me too. If you click the "Archive" button in the "All sets" area and switch to the "Archive" area there is no set containing the card that was archived. If you switch back to the "All sets" area then a new set is created with the card that was archived.

**Comment by azizkayumov** [comment]
Sorry for the inconvenience. I was using the older version on my phone. It turns out it is the external lib's issue.

**Comment by azizkayumov** [comment]
Published the fix to Google Play now. Let me know if it works for you.

**Comment by greyboxgt** [comment]
I do not see the update in Google Play, the latest version there is still v0.3.6.

**Comment by azizkayumov** [comment]
it is being reviewed on Google Play and should be available soon.

**Comment by greyboxgt** [comment]
The issue is fixed in 0.3.7, thank you very much!!!
