### ISSUE TITLE
Navigation between the cards in the editing and study modules

### ISSUE THREAD

**Issue by greyboxgt** [azizkayumov/Flashcard-Maker-Android#41]
When moving to the next or previous card in the card set, we use the < and > buttons or swiping. But if we want to get to a certain card somewhere in the middle of the card set and if we have a lot of cards in the set, this way navigation becomes slow and inconvenient. Tapping too fast does not produce a reliable result, at least in the editing module. 

The suggestion is to use tap and hold feature. When a user taps and holds the button, the display shows the current card, but the card number changes, maybe, 4 numbers per second? After reaching the maximum or the minimum, cycles and continues until the user releases the button. After that the appropriate card is displayed. 

And also sometimes we may want to go to the first or the last card in the set directly. In this case we may use a double-tap on the appropriate <  or  >  button in the editing or study module.

**Comment by azizkayumov** [comment]
Thank you for your feedback. 
I'll try to push them in the next commit soon.

**Comment by azizkayumov** [comment]
This commit adds the press to fast-scroll cards gesture to Editing module. 
If a user presses < or > buttons and hold, it keeps scrolling until it reaches the end and stops. As you mentioned above, 4 cards per second are scrolled on the press action. A single tap works as usual. 
I was thinking this "fast-scrolling" feature must end somewhere, so stopping it in the end would be a better user experience than the double-tap action.

Published an update on Google Play, let me know if it works for you.

**Comment by greyboxgt** [comment]
Works great, thank you very much!

**Comment by Engineerator** [comment]
Thank you very much for adding this wonderful feature!

I noticed that swiping motion swipes the cards, but the numbers on the bottom left stay the same until the swiping stops. Is this something that can be fixed?

**Comment by azizkayumov** [comment]
It is possible to detect the current mostly-visible card number with this implementation. Updating the current card number during the scroll or fling actions may complicate the code.

**Comment by azizkayumov** [comment]
Let's close this issue for now, feel free to open it if something comes up.
